# Dockerfile.frontend

FROM node:12 AS builder

WORKDIR /app

COPY . .

RUN npm install -f
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist/front /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
