# Dockerfile.backend

# Use the Node.js 18 image as the base
FROM node:20

# Set working directory
WORKDIR /app

# Copy the backend source code to the container
COPY . .

# Install dependencies
RUN npm install -f

# Expose the port your backend uses
EXPOSE 3000

# Start the backend
CMD ["npm", "start"]
